---
apiVersion: v1
automountServiceAccountToken: true
kind: ServiceAccount
metadata:
  name: bashgress

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: bashgress
rules:
- apiGroups:
  - networking.k8s.io
  resources:
  - ingresses
  verbs:
  - list
  - get

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: bashgress
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: bashgress
subjects:
- kind: ServiceAccount
  name: bashgress
